# Generated by Django 5.2.8 on 2025-11-28 14:52

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLibrary",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name"
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_libraries",
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Audit Libraries",
            },
        ),
        migrations.CreateModel(
            name="Criterion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("public_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "audit_library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criterias",
                        to="audits.auditlibrary",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Criteria",
            },
        ),
        migrations.CreateModel(
            name="ProjectAudit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "audit_library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="audits.auditlibrary",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audits",
                        to="organization.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectAuditCriterion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_HANDLED_YET", "⚪️ Not Handled Yet"),
                            ("NOT_COMPLIANT", "🔴 Not Compliant"),
                            ("PARTIALLY_COMPLIANT", "🟡 Partially Compliant"),
                            ("COMPLIANT", "🟢 Compliant"),
                        ],
                        default="NOT_HANDLED_YET",
                        max_length=255,
                    ),
                ),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_audits",
                        to="audits.criterion",
                    ),
                ),
                (
                    "project_audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="audits.projectaudit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectAuditCriterionComment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("comment", models.TextField(blank=True, default="")),
                (
                    "project_audit_criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="audits.projectauditcriterion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_audit_criterion_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectAuditCriterionPrompt",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("session_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("name", models.CharField(default="Prompt", max_length=255)),
                ("prompt", models.JSONField(blank=True, default=dict)),
                (
                    "project_audit_criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompts",
                        to="audits.projectauditcriterion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "criteria",
                    models.ManyToManyField(
                        blank=True, related_name="tags", to="audits.criterion"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="auditlibrary",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="unique_organization_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="auditlibrary",
            constraint=models.UniqueConstraint(
                fields=("organization", "slug"), name="unique_organization_slug"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="criterion",
            unique_together={("audit_library", "public_id")},
        ),
    ]
