# Generated by Django 5.2.8 on 2026-01-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.TextField(blank=True, default="", verbose_name="Comment"),
        ),
    ]
