# Generated by Django 5.2.8 on 2026-01-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0002_alter_comment_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectaudit",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "🟢 Active"), ("ARCHIVED", "� Archived")],
                default="ACTIVE",
                max_length=255,
                verbose_name="Status",
            ),
        ),
    ]
