# Generated by Django 5.2.8 on 2026-01-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0002_alter_comment_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectauditcriterion",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT_HANDLED_YET", "⚪️ Not Handled Yet"),
                    ("NOT_COMPLIANT", "🔴 Not Compliant"),
                    ("PARTIALLY_COMPLIANT", "🟡 Partially Compliant"),
                    ("COMPLIANT", "🟢 Compliant"),
                    ("NOT_APPLICABLE", "❌ Not Applicable"),
                ],
                default="NOT_HANDLED_YET",
                max_length=255,
            ),
        ),
    ]
