# Generated by Django 5.2.8 on 2025-11-23 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0002_conversation_message"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectAudit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "audit_library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="audits.auditlibrary",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audits",
                        to="organization.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
