# Generated by Django 5.2.8 on 2026-02-06 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0003_projectaudit_status"),
        ("organization", "0003_alter_project_description_alter_project_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlibrary",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_libraries",
                to="organization.organization",
            ),
        ),
    ]
