# Generated by Django 5.2.8 on 2026-02-06 12:27

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0004_alter_auditlibrary_organization"),
        ("organization", "0003_alter_project_description_alter_project_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLibraryTag",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="auditlibrary",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="audit_libraries", to="audits.auditlibrarytag"
            ),
        ),
        migrations.CreateModel(
            name="CriterionTag",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="criterion",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="criteria", to="audits.criteriontag"
            ),
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
