# Generated by Django 5.2.8 on 2026-02-14 07:06

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0004_alter_auditlibrary_organization"),
        ("organization", "0003_alter_project_description_alter_project_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="criteria",
        ),
        migrations.AddField(
            model_name="auditlibrary",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="audit_libraries", to="audits.tag"
            ),
        ),
        migrations.AddField(
            model_name="criterion",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="criteria", to="audits.tag"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.organization",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="name"
            ),
        ),
    ]
