# Generated by Django 5.2.8 on 2025-11-28 09:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0004_projectauditcriterion_projectauditcriterioncomment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectauditcriterionprompt",
            name="session_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
