# Generated by Django 5.2.8 on 2025-11-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0005_add_session_id_to_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectauditcriterionprompt",
            name="name",
            field=models.CharField(default="Prompt", max_length=255),
        ),
    ]
