# Generated by Django 5.2.8 on 2025-11-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0006_projectauditcriterionprompt_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectauditcriterion",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT_HANDLED_YET", "⚪️ Not Handled Yet"),
                    ("NOT_COMPLIANT", "🔴 Not Compliant"),
                    ("PARTIALLY_COMPLIANT", "🟡 Partially Compliant"),
                    ("COMPLIANT", "🟢 Compliant"),
                ],
                default="NOT_HANDLED_YET",
                max_length=255,
            ),
        ),
    ]
