# Generated by Django 5.2.8 on 2025-11-28 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0007_alter_projectauditcriterion_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="conversation",
        ),
        migrations.DeleteModel(
            name="Conversation",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
