# Generated by Django 5.2.8 on 2026-01-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0002_alter_organization_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
    ]
